[package]
name = "hashums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
sha2 = "0.9.8"
termcolor = "1.1.2"
walkdir = "2.3.2"
